services:
  container-dev:
    build: .
    container_name: workspace
    volumes:
      - dados_do_projeto:/workspace
      - ${HOME}/.ssh:/root/.ssh:ro
      - ${HOME}/.zshrc:/root/.zshrc
      - ${HOME}/.oh-my-zsh:/root/.oh-my-zsh
      
    working_dir: /workspace 
    stdin_open: true 
    tty: true 
    command: /bin/zsh

volumes:
  dados_do_projeto:
    name: python
